import type { ChoiceItem, ProjectDocument } from "@/types/project";

function createChoiceItem(id: string, label: string): ChoiceItem {
  return { id, label, dynamicTextVarId: null };
}

const demoListItems: ChoiceItem[] = [
  createChoiceItem("item_basic_paint", "Basic Paint"),
  createChoiceItem("item_text", "Text"),
  createChoiceItem("item_variable_box", "Variable box"),
  createChoiceItem("item_realtime_graph", "Realtime graph"),
  createChoiceItem("item_menu", "Menu"),
  createChoiceItem("item_notice_box", "Notice box"),
  createChoiceItem("item_tuning_curve", "Tuning curve"),
  createChoiceItem("item_polar_coordinates", "Polar coordinates"),
];

const demoMenuItems: ChoiceItem[] = [
  createChoiceItem("menu_item_1", "Item 1"),
  createChoiceItem("menu_item_2", "Item 2"),
  createChoiceItem("menu_item_3", "Item 3"),
  createChoiceItem("menu_item_4", "Item 4"),
  createChoiceItem("menu_item_5", "Item 5"),
  createChoiceItem("menu_item_6", "Item 6"),
  createChoiceItem("menu_item_7", "Item 7"),
  createChoiceItem("menu_item_8", "Item 8"),
];

const demoSubMenuItems: ChoiceItem[] = [
  createChoiceItem("submenu_item_1", "Sub 1"),
  createChoiceItem("submenu_item_2", "Sub 2"),
  createChoiceItem("submenu_item_3", "Sub 3"),
  createChoiceItem("submenu_item_4", "Sub 4"),
];

export function createDefaultProject(): ProjectDocument {
  return {
    version: 1,
    project: {
      name: "simplegui-demomainprocess-demo",
      createdAt: "2026-05-28T10:00:00+08:00",
      updatedAt: "2026-05-28T10:00:00+08:00",
    },
    screen: {
      width: 128,
      height: 64,
      foreground: "#000000",
      background: "#ffffff",
      buffered: true,
    },
    resources: [
      {
        id: "res_info_16",
        name: "Information 16",
        kind: "icon",
        source: "SGUI_RES_ICON_INFORMATION_16",
        bitmap: {
          width: 16,
          height: 16,
          rows: [
            "1111111111111111",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1011011111111101",
            "1011011111111101",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1000000000000001",
            "1111111111111111",
          ],
        },
      },
    ],
    variables: [
      { id: "var_demo_number", name: "Variable Number", type: "int", initial: 13, min: -50, max: 100, step: 1, readonly: false },
      { id: "var_demo_text", name: "Variable Text", type: "string", initial: "ABCDEFG1234567890+-*/OPQ", length: 24, readonly: false },
      { id: "var_graph_value", name: "Graph Value", type: "int", initial: -90, min: -100, max: 100, step: 1, readonly: false },
      { id: "var_graph_display", name: "Graph Display", type: "int", initial: 0, min: -100, max: 100, step: 1, readonly: false },
      { id: "var_graph_step", name: "Graph Step", type: "int", initial: 9, min: -100, max: 100, step: 1, readonly: false },
      { id: "var_clock_hour", name: "Clock Hour", type: "int", initial: 10, min: 0, max: 23, step: 1, readonly: false },
      { id: "var_clock_minute", name: "Clock Minute", type: "int", initial: 8, min: 0, max: 59, step: 1, readonly: false },
      { id: "var_clock_second", name: "Clock Second", type: "int", initial: 30, min: 0, max: 59, step: 1, readonly: false },
    ],
    timers: [
      { id: "timer_graph", name: "Realtime Graph Tick", intervalMs: 200, repeat: true, enabledOnStart: false, targetPictureId: "pic_realtime_graph" },
      { id: "timer_clock", name: "RTC Tick", intervalMs: 1000, repeat: true, enabledOnStart: false, targetPictureId: "pic_polar_coordinates" },
    ],
    pictures: [
      {
        id: "pic_demo_list",
        name: "List Components",
        title: "List Components",
        widgets: [
          {
            id: "w_demo_list",
            type: "list",
            name: "Demo List",
            rect: { x: 0, y: 0, width: 128, height: 64 },
            visible: true,
            enabled: true,
            focusable: true,
            zIndex: 0,
            props: {
              title: "List Components",
              font: "GB2312_FZXS12",
              items: demoListItems,
              selectedIndex: 0,
              showScrollbar: true,
            },
          },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_basic_paint",
        name: "Basic Paint",
        title: "Basic Paint",
        widgets: [
          { id: "w_basic_1", type: "shape", name: "Line 1", rect: { x: 0, y: 0, width: 128, height: 1 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "hline", fill: false, radius: 0 } },
          { id: "w_basic_2", type: "shape", name: "Line 2", rect: { x: 0, y: 5, width: 128, height: 1 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "hline", fill: false, radius: 0 } },
          { id: "w_basic_3", type: "shape", name: "Line 3", rect: { x: 0, y: 10, width: 128, height: 1 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "hline", fill: false, radius: 0 } },
          { id: "w_basic_rect_1", type: "shape", name: "Rect 1", rect: { x: 1, y: 1, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: false, radius: 4 } },
          { id: "w_basic_rect_2", type: "shape", name: "Rect 2", rect: { x: 1, y: 22, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: true, radius: 4 } },
          { id: "w_basic_rect_3", type: "shape", name: "Rect 3", rect: { x: 1, y: 43, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: false, radius: 4 } },
          { id: "w_basic_rect_thin_1", type: "shape", name: "Thin Rect 1", rect: { x: 37, y: 1, width: 5, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: false, radius: 0 } },
          { id: "w_basic_rect_thin_2", type: "shape", name: "Thin Rect 2", rect: { x: 37, y: 22, width: 5, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: true, radius: 0 } },
          { id: "w_basic_rect_thin_3", type: "shape", name: "Thin Rect 3", rect: { x: 37, y: 43, width: 5, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "rect", fill: true, radius: 0 } },
          { id: "w_basic_circle_1", type: "shape", name: "Circle 1", rect: { x: 49, y: 1, width: 18, height: 18 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "circle", fill: false, radius: 8 } },
          { id: "w_basic_circle_2", type: "shape", name: "Circle 2", rect: { x: 49, y: 22, width: 18, height: 18 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "circle", fill: true, radius: 8 } },
          { id: "w_basic_circle_3", type: "shape", name: "Circle 3", rect: { x: 49, y: 43, width: 18, height: 18 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "circle", fill: false, radius: 8 } },
          { id: "w_basic_round_1", type: "shape", name: "Round 1", rect: { x: 70, y: 1, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: false, radius: 4 } },
          { id: "w_basic_round_2", type: "shape", name: "Round 2", rect: { x: 70, y: 22, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: true, radius: 4 } },
          { id: "w_basic_round_3", type: "shape", name: "Round 3", rect: { x: 70, y: 43, width: 30, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: false, radius: 4 } },
          { id: "w_basic_small_1", type: "shape", name: "Small 1", rect: { x: 105, y: 1, width: 20, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: false, radius: 6 } },
          { id: "w_basic_small_2", type: "shape", name: "Small 2", rect: { x: 105, y: 22, width: 20, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: true, radius: 6 } },
          { id: "w_basic_small_3", type: "shape", name: "Small 3", rect: { x: 105, y: 43, width: 20, height: 20 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { kind: "roundedRect", fill: true, radius: 6 } },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_text",
        name: "Text",
        title: "Text",
        widgets: [
          { id: "w_text_mininum", type: "textLabel", name: "Mini Num", rect: { x: 1, y: 1, width: 60, height: 6 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "1+2+8/4*5=13", font: "SGUI_DEFAULT_FONT_MiniNum", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_text_8", type: "textLabel", name: "Text 8", rect: { x: 1, y: 12, width: 60, height: 8 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "Hello Simple GUI.", font: "SGUI_DEFAULT_FONT_8", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_text_12_reverse", type: "textLabel", name: "Text 12", rect: { x: 1, y: 22, width: 60, height: 12 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "Welcome!", font: "SGUI_DEFAULT_FONT_12", drawMode: "reverse", multiline: false, align: "left", textVarId: null } },
          { id: "w_text_12_normal", type: "textLabel", name: "Text 12 B", rect: { x: 1, y: 35, width: 60, height: 12 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "I don't like this.", font: "GB2312_FZXS12", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_text_multi", type: "textLabel", name: "Multi", rect: { x: 64, y: 1, width: 62, height: 62 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "Multiline demo text with 12-pixel font.", font: "GB2312_FZXS12", drawMode: "normal", multiline: true, align: "left", textVarId: null } },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_variable_box",
        name: "Variable box",
        title: "Variable box",
        widgets: [
          { id: "w_var_frame", type: "shape", name: "Frame", rect: { x: 0, y: 0, width: 128, height: 64 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "rect", fill: false, radius: 0 } },
          { id: "w_var_frame_inner", type: "shape", name: "Inner Frame", rect: { x: 2, y: 2, width: 124, height: 60 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "rect", fill: false, radius: 0 } },
          { id: "w_var_divider", type: "shape", name: "Divider", rect: { x: 3, y: 17, width: 122, height: 1 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { kind: "hline", fill: false, radius: 0 } },
          { id: "w_var_title", type: "textLabel", name: "Var Title", rect: { x: 4, y: 4, width: 120, height: 12 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { text: "Variable box", font: "GB2312_FZXS12", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_var_notice", type: "notice", name: "Var Notice", rect: { x: 5, y: 5, width: 118, height: 54 }, visible: true, enabled: true, focusable: false, zIndex: 3, props: { text: "Press TAB to switch focus.\nUp&Down to change value.\nSend \"SPACE\" to continue.", font: "SGUI_DEFAULT_FONT_8", iconResourceId: "res_info_16", textOffset: 0, autoFit: true, frame: true } },
          { id: "w_var_number", type: "numberVariableBox", name: "Variable Number", rect: { x: 10, y: 24, width: 108, height: 8 }, visible: true, enabled: true, focusable: true, zIndex: 2, props: { font: "SGUI_DEFAULT_FONT_8", alignment: "center", min: -50, max: 100, valueVarId: "var_demo_number", step: 1 } },
          { id: "w_var_text", type: "textVariableBox", name: "Variable Text", rect: { x: 10, y: 40, width: 108, height: 12 }, visible: true, enabled: true, focusable: true, zIndex: 2, props: { font: "SGUI_DEFAULT_FONT_12", textVarId: "var_demo_text", length: 24, charSet: "ascii", maskChar: "*", focusIndex: 0 } },
        ],
        enterActions: [
          { type: "setVariable", variableId: "var_demo_number", value: 13 },
          { type: "setVariable", variableId: "var_demo_text", value: "ABCDEFG1234567890+-*/OPQ" },
          { type: "setWidgetProp", widgetId: "w_var_notice", prop: "visible", value: true },
          { type: "setWidgetProp", widgetId: "w_var_number", prop: "visible", value: true },
          { type: "setWidgetProp", widgetId: "w_var_text", prop: "visible", value: true },
          { type: "setWidgetProp", widgetId: "w_var_number", prop: "enabled", value: true },
          { type: "setWidgetProp", widgetId: "w_var_text", prop: "enabled", value: true },
        ],
        leaveActions: [],
      },
      {
        id: "pic_realtime_graph",
        name: "Realtime graph",
        title: "Realtime graph",
        widgets: [
          { id: "w_graph_title", type: "textLabel", name: "Graph Title", rect: { x: 1, y: 1, width: 110, height: 8 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "Realtime graph", font: "SGUI_DEFAULT_FONT_8", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_graph_demo", type: "realtimeGraph", name: "Realtime Graph", rect: { x: 1, y: 11, width: 126, height: 46 }, visible: true, enabled: true, focusable: false, zIndex: 1, props: { valueVarId: "var_graph_value", min: -100, max: 100, xStepPixel: 6, enableBaseline: true, baselineValue: 0, capacity: 21 } },
          { id: "w_graph_value", type: "textLabel", name: "Graph Value Text", rect: { x: 1, y: 58, width: 30, height: 6 }, visible: true, enabled: true, focusable: false, zIndex: 2, props: { text: "", font: "SGUI_DEFAULT_FONT_MiniNum", drawMode: "normal", multiline: false, align: "left", textVarId: "var_graph_display" } },
        ],
        enterActions: [
          { type: "setVariable", variableId: "var_graph_value", value: -90 },
          { type: "setVariable", variableId: "var_graph_display", value: 0 },
          { type: "setVariable", variableId: "var_graph_step", value: 9 },
          { type: "clearGraphBuffer", widgetId: "w_graph_demo" },
          { type: "startTimer", timerId: "timer_graph" },
        ],
        leaveActions: [{ type: "stopTimer", timerId: "timer_graph" }],
      },
      {
        id: "pic_menu",
        name: "Menu",
        title: "Menu",
        widgets: [
          { id: "w_menu_main", type: "menu", name: "Main Menu", rect: { x: 0, y: 0, width: 48, height: 60 }, visible: true, enabled: true, focusable: true, zIndex: 1, props: { font: "SGUI_DEFAULT_FONT_8", items: demoMenuItems, selectedIndex: 0, frame: true, popupParentWidgetId: null } },
          { id: "w_menu_sub", type: "menu", name: "Sub Menu", rect: { x: 0, y: 0, width: 50, height: 34 }, visible: false, enabled: false, focusable: false, zIndex: 2, props: { font: "SGUI_DEFAULT_FONT_8", items: demoSubMenuItems, selectedIndex: 0, frame: true, popupParentWidgetId: "w_menu_main" } },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_notice",
        name: "Notice box",
        title: "Notice box",
        widgets: [
          { id: "w_notice_box", type: "notice", name: "Notice", rect: { x: 5, y: 5, width: 118, height: 54 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "This is a test notice.", font: "GB2312_FZXS12", iconResourceId: null, textOffset: 0, autoFit: true, frame: true } },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_curve",
        name: "Tuning curve",
        title: "Tuning curve",
        widgets: [
          { id: "w_curve_title", type: "textLabel", name: "Curve Title", rect: { x: 1, y: 1, width: 120, height: 8 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { text: "Press TAB to change focus.", font: "SGUI_DEFAULT_FONT_8", drawMode: "normal", multiline: false, align: "left", textVarId: null } },
          { id: "w_curve_demo", type: "curve", name: "Curve", rect: { x: 0, y: 10, width: 128, height: 44 }, visible: true, enabled: true, focusable: true, zIndex: 1, props: { xMin: -100, xMax: 100, yMin: -100, yMax: 100, points: [ { x: -100, y: -100 }, { x: -75, y: -100 }, { x: 0, y: 0 }, { x: 50, y: 25 }, { x: 100, y: 75 } ], focusedIndex: 0, argumentValue: -100, font: "SGUI_DEFAULT_FONT_8", headerText: "Press TAB to change focus." } },
        ],
        enterActions: [],
        leaveActions: [],
      },
      {
        id: "pic_polar_coordinates",
        name: "Polar coordinates",
        title: "Polar coordinates",
        widgets: [
          { id: "w_clock_demo", type: "polarClock", name: "Polar Clock", rect: { x: 0, y: 0, width: 128, height: 64 }, visible: true, enabled: true, focusable: false, zIndex: 0, props: { timeSource: "variables", hourVarId: "var_clock_hour", minuteVarId: "var_clock_minute", secondVarId: "var_clock_second", font: "SGUI_DEFAULT_FONT_12", dialCenterX: 31, dialCenterY: 31, radius: 28, textX: 75, textY: 25 } },
        ],
        enterActions: [{ type: "startTimer", timerId: "timer_clock" }],
        leaveActions: [{ type: "stopTimer", timerId: "timer_clock" }],
      },
    ],
    rules: [
      { id: "r_demo_list_up", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "up", widgetId: "w_demo_list" }, actions: [{ type: "selectPrev", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_demo_list_down", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "down", widgetId: "w_demo_list" }, actions: [{ type: "selectNext", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_0", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 0 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_basic_paint" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_1", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 1 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_text" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_2", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 2 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_variable_box" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_3", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 3 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_realtime_graph" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_4", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 4 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_menu" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_5", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 5 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_notice" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_6", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 6 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_curve" }], stopAfterMatch: true },
      { id: "r_demo_list_confirm_7", pictureId: "pic_demo_list", event: { kind: "onWidgetConfirm", widgetId: "w_demo_list" }, condition: { mode: "all", items: [{ kind: "widgetSelected", widgetId: "w_demo_list", index: 7 }] }, actions: [{ type: "gotoPicture", pictureId: "pic_polar_coordinates" }], stopAfterMatch: true },
      { id: "r_demo_list_insert", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "insert", widgetId: "w_demo_list" }, actions: [{ type: "selectNext", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_demo_list_delete", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "delete", widgetId: "w_demo_list" }, actions: [{ type: "selectPrev", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_demo_list_home", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "home", widgetId: "w_demo_list" }, actions: [{ type: "selectPrev", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_demo_list_end", pictureId: "pic_demo_list", event: { kind: "onKeyPress", key: "end", widgetId: "w_demo_list" }, actions: [{ type: "selectNext", widgetId: "w_demo_list" }], stopAfterMatch: true },
      { id: "r_basic_back", pictureId: "pic_basic_paint", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_text_back", pictureId: "pic_text", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_var_space", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "space" }, actions: [{ type: "setWidgetProp", widgetId: "w_var_notice", prop: "visible", value: false }], stopAfterMatch: true },
      { id: "r_var_tab", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "tab" }, actions: [{ type: "focusNext" }], stopAfterMatch: true },
      { id: "r_var_up_number", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "up", widgetId: "w_var_number" }, actions: [{ type: "increaseVariable", variableId: "var_demo_number", step: 1 }], stopAfterMatch: true },
      { id: "r_var_down_number", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "down", widgetId: "w_var_number" }, actions: [{ type: "decreaseVariable", variableId: "var_demo_number", step: 1 }], stopAfterMatch: true },
      { id: "r_var_left_text", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "left", widgetId: "w_var_text" }, actions: [{ type: "focusPrev", widgetId: "w_var_text" }], stopAfterMatch: true },
      { id: "r_var_right_text", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "right", widgetId: "w_var_text" }, actions: [{ type: "focusNext", widgetId: "w_var_text" }], stopAfterMatch: true },
      { id: "r_var_up_text", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "up", widgetId: "w_var_text" }, actions: [{ type: "textCharNext", widgetId: "w_var_text" }], stopAfterMatch: true },
      { id: "r_var_down_text", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "down", widgetId: "w_var_text" }, actions: [{ type: "textCharPrev", widgetId: "w_var_text" }], stopAfterMatch: true },
      { id: "r_var_escape", pictureId: "pic_variable_box", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_graph_timer", pictureId: "pic_realtime_graph", event: { kind: "onTimer", timerId: "timer_graph" }, actions: [{ type: "setVariableFromVariable", variableId: "var_graph_display", fromVariableId: "var_graph_value" }, { type: "pushGraphValue", widgetId: "w_graph_demo", valueSource: "fromVariable", fromVariableId: "var_graph_display" }, { type: "addVariableFromVariable", variableId: "var_graph_value", fromVariableId: "var_graph_step" }], stopAfterMatch: true },
      { id: "r_graph_reverse_high", pictureId: "pic_realtime_graph", event: { kind: "onValueChange", variableId: "var_graph_value" }, condition: { mode: "all", items: [{ kind: "variableCompare", variableId: "var_graph_value", operator: "gte", value: 90 }] }, actions: [{ type: "negateVariable", variableId: "var_graph_step" }], stopAfterMatch: true },
      { id: "r_graph_reverse_low", pictureId: "pic_realtime_graph", event: { kind: "onValueChange", variableId: "var_graph_value" }, condition: { mode: "all", items: [{ kind: "variableCompare", variableId: "var_graph_value", operator: "lte", value: -90 }] }, actions: [{ type: "negateVariable", variableId: "var_graph_step" }], stopAfterMatch: true },
      { id: "r_graph_back", pictureId: "pic_realtime_graph", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_menu_up", pictureId: "pic_menu", event: { kind: "onKeyPress", key: "up", widgetId: "w_menu_main" }, condition: { mode: "all", items: [{ kind: "widgetVisible", widgetId: "w_menu_sub", visible: false }] }, actions: [{ type: "selectPrev", widgetId: "w_menu_main" }], stopAfterMatch: true },
      { id: "r_menu_down", pictureId: "pic_menu", event: { kind: "onKeyPress", key: "down", widgetId: "w_menu_main" }, condition: { mode: "all", items: [{ kind: "widgetVisible", widgetId: "w_menu_sub", visible: false }] }, actions: [{ type: "selectNext", widgetId: "w_menu_main" }], stopAfterMatch: true },
      { id: "r_menu_confirm", pictureId: "pic_menu", event: { kind: "onWidgetConfirm", widgetId: "w_menu_main" }, condition: { mode: "all", items: [{ kind: "widgetVisible", widgetId: "w_menu_sub", visible: false }] }, actions: [{ type: "setWidgetProp", widgetId: "w_menu_sub", prop: "visible", value: true }, { type: "setWidgetProp", widgetId: "w_menu_sub", prop: "enabled", value: true }], stopAfterMatch: true },
      { id: "r_menu_close_sub", pictureId: "pic_menu", event: { kind: "onKeyPress", key: "esc" }, condition: { mode: "all", items: [{ kind: "widgetVisible", widgetId: "w_menu_sub", visible: true }] }, actions: [{ type: "setWidgetProp", widgetId: "w_menu_sub", prop: "visible", value: false }, { type: "setWidgetProp", widgetId: "w_menu_sub", prop: "enabled", value: false }], stopAfterMatch: true },
      { id: "r_menu_back", pictureId: "pic_menu", event: { kind: "onKeyPress", key: "esc" }, condition: { mode: "all", items: [{ kind: "widgetVisible", widgetId: "w_menu_sub", visible: false }] }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_notice_back", pictureId: "pic_notice", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_curve_tab", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "tab" }, actions: [{ type: "focusNext" }], stopAfterMatch: true },
      { id: "r_curve_shift_insert_before", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "shiftInsert", widgetId: "w_curve_demo" }, actions: [{ type: "focusPrev", widgetId: "w_curve_demo" }], stopAfterMatch: true },
      { id: "r_curve_insert_after", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "insert", widgetId: "w_curve_demo" }, actions: [{ type: "focusNext", widgetId: "w_curve_demo" }], stopAfterMatch: true },
      { id: "r_curve_delete", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "delete", widgetId: "w_curve_demo" }, actions: [{ type: "focusPrev", widgetId: "w_curve_demo" }], stopAfterMatch: true },
      { id: "r_curve_home", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "home", widgetId: "w_curve_demo" }, actions: [{ type: "focusPrev", widgetId: "w_curve_demo" }], stopAfterMatch: true },
      { id: "r_curve_end", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "end", widgetId: "w_curve_demo" }, actions: [{ type: "focusNext", widgetId: "w_curve_demo" }], stopAfterMatch: true },
      { id: "r_curve_back", pictureId: "pic_curve", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_polar_back", pictureId: "pic_polar_coordinates", event: { kind: "onKeyPress", key: "esc" }, actions: [{ type: "goBack" }], stopAfterMatch: true },
      { id: "r_clock_timer", pictureId: "pic_polar_coordinates", event: { kind: "onTimer", timerId: "timer_clock" }, actions: [{ type: "increaseVariable", variableId: "var_clock_second", step: 1 }], stopAfterMatch: true },
    ],
    simulator: {
      startPictureId: "pic_demo_list",
      keyMode: "dual",
      showGrid: true,
      fps: 20,
    },
  };
}
